GET http://localhost:3001/api/teachers

###

POST http://localhost:3001/api/teachers
Content-Type: application/json

{
    "name": "Maxym",
    "password":"123456",
    "email":"maxym@gmail.com"

}
###
DELETE http://localhost:3001/api/subjects/660e71a0c629c0b7a0e9e216