GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/auth/users
Content-Type: application/json

{
    "username":"Ren",
    "email":"ren@gmail.com",
    "password":"222222",
    "role":"student"
}
###
DELETE http://localhost:3001/api/subjects/660e71a0c629c0b7a0e9e216

###
POST http://localhost:3001/api/subjects
Content-Type: application/json

{
    "name":"Фізика"
}
###

